spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth-service-route
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
        - id: task-service-route
          uri: lb://task-service
          predicates:
            - Path=/api/tasks/**
server:
  port: 8080
