keySetURI: http://localhost:8071/oauth2/jwks
spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns:
              - http://localhost:5173
              - http://localhost:5174
              - https://fixly-meow.ru
              - https://fixly-meow.ru:5050
              - https://fixly-meow.ru:8092
              - https://api.fixly-meow.ru
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth-service-direct
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth-service/**
          filters:
            - StripPrefix=1
            - PrefixPath=/api
        - id: auth-service-api
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/auth-service/**
          filters:
            - StripPrefix=2
            - PrefixPath=/api
        - id: minio-media
          uri: http://minio:9000
          predicates:
            - Path=/media/**
          filters:
            - AddResponseHeader=Access-Control-Allow-Origin, *
            - AddResponseHeader=Access-Control-Allow-Headers, *
            - AddResponseHeader=Access-Control-Allow-Methods, GET,PUT,POST,DELETE,OPTIONS
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
management:
  metrics.tags.application: ${spring.application.name}
  endpoint:
    gateway:
      access: unrestricted
    web:
      exposure:
        include: gateway
  endpoints:
    web:
      exposure:
        include: prometheus,gateway,health,info
#      routes:
#        - id: auth-service-route
#          uri: lb://auth-service
#          predicates:
#            - Path=/api/auth/**
#        - id: task-service-route
#          uri: lb://task-service
#          predicates:
#            - Path=/api/tasks/**
server:
  port: 8075
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8070/eureka/
  instance:
    prefer-ip-address: true
