spring:
  security:
    oauth2:
      client:
        registration:
          auth-server:
            client-id: gateway-server
            client-secret: secret
            authorization-grant-type: authorization_code
            scope: openid,tasks.read
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          auth-server:
            issuer-uri: http://auth-service:8071
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
management:
  metrics.tags.application: ${spring.application.name}
  endpoint:
    gateway:
      access: unrestricted
  endpoints:
    web:
      exposure:
        include: prometheus,gateway,health,info
#      routes:
#        - id: auth-service-route
#          uri: lb://auth-service
#          predicates:
#            - Path=/api/auth/**
#        - id: task-service-route
#          uri: lb://task-service
#          predicates:
#            - Path=/api/tasks/**
server:
  port: 8080
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8070/eureka/
  instance:
    prefer-ip-address: true