apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.38.0 (HEAD)
  labels:
    io.kompose.service: gateway-server
  name: gateway-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: gateway-server
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.38.0 (HEAD)
      labels:
        io.kompose.service: gateway-server
    spec:
      containers:
        - env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://eureka-server:8070/eureka/
            - name: KEYSETURI
              value: http://auth-service:8071/oauth2/jwks
          image: fixly-meow.ru:443/degree_manager-gateway-server:latest
          name: gateway-server
          ports:
            - containerPort: 8075
              protocol: TCP
      restartPolicy: Always
