scrape_configs:
  - job_name: spring
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - host.docker.internal:8080
          - host.docker.internal:8071
#          - host.docker.internal:8082
          - host.docker.internal:8070
