server {
    listen 443 ssl http2;
    server_name fixly-meow.ru;

    root /var/www/fixly-frontend;
    index index.html;

    ssl_certificate     /opt/registry/certs/certificate.crt;
    ssl_certificate_key /opt/registry/certs/certificate.key;
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;

    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /assets/ {
        try_files $uri =404;
        access_log off;
    }
}

server {
    listen 5050 ssl;
    server_name fixly-meow.ru;

    root /var/www/fixly-admin;
    index index.html;

    ssl_certificate     /opt/registry/certs/certificate.crt;
    ssl_certificate_key /opt/registry/certs/certificate.key;
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;

    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
