apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.38.0 (HEAD)
  labels:
    io.kompose.service: eureka-server
  name: eureka-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: eureka-server
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.38.0 (HEAD)
      labels:
        io.kompose.service: eureka-server
    spec:
      containers:
        - env:
            - name: SPRING_DATASOURCE_PASSWORD
              value: postgres
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/task_app
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
          image: fixly-meow.ru:5000/degree_manager-eureka-server:latest
          name: eureka-server
          ports:
            - containerPort: 8070
              protocol: TCP
      restartPolicy: Always
